language: julia

julia:
  - 1.5

os:
  - linux

notifications:
  email: false

addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libblas-dev
        - libgmp-dev
        - libglpk-dev

sudo: false

# script:
#   - julia -e 'Pkg.clone("https://github.com/mlakolar/ProximalBase.jl"); Pkg.clone("https://github.com/mlakolar/CoordinateDescent.jl"); Pkg.clone(pwd()); Pkg.build("CovSel"); Pkg.test("CovSel"; coverage=true)'
# after_success:
#     - echo $TRAVIS_JULIA_VERSION
#     - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("CovSel")); using Coverage; Codecov.submit(process_folder())'

after_success:
    - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
