language: julia
julia:
  - 0.6
os:
  - linux
notifications:
  email: false
addons:
    apt_packages:
        - gfortran
sudo: false
script:
  - julia -e 'Pkg.clone("https://github.com/mlakolar/ProximalBase.jl"); Pkg.clone("https://github.com/mlakolar/CoordinateDescent.jl"); Pkg.clone(pwd()); Pkg.build("CovSel"); Pkg.test("CovSel"; coverage=true)'
# after_success:
#     - echo $TRAVIS_JULIA_VERSION
#     - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("CovSel")); using Coverage; Codecov.submit(process_folder())'
